project:
  type: website

website:
  title: "DS QuickRef"
  search: 
    location: sidebar
    type: textbox
  sidebar:
    style: "floating"
    search: true
    logo: dsqr_logo.png
    logo-alt: "DS QuickRef"
    contents:
      - text: "Introduction"
        href: index.qmd

      - section: "Workflows"
        contents:
          - workflows/index.qmd
          - workflows/supervised_learning.ipynb
      
      - text: "Metrics"
        href: metrics.qmd

      - text: "Common DS Problems"
        href: common_problems.qmd

      - text: "Glossary"
        href: glossary.qmd

      - text: "References"
        href: references.qmd

language: 
  search-text-placeholder: Search

format:
  html:
    theme:
      - materia
      - brand
      - styles.scss
    toc: true
    font:
      sans: "Segoe UI"
    fontsize: 1rem
    line-height: 1.6
    grid:
      sidebar-width: 400px
      body-width: 800px
      margin-width: 300px
      gutter-width: 2rem
    smooth-scroll: true

execute:
  enabled: true
