project:
  type: book

book:
  title: "ds-quickref"
  author: "Dmitriiy Bolotovs"
  date: "7/9/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true


