project:
  type: website

website:
  title: "DS QuickRef"
  search: 
    location: sidebar
    type: textbox
  sidebar:
    style: "floating"
    search: true
    logo: images/dsqr_logo.png
    logo-alt: "DS QuickRef"
    contents:
      - text: "Introduction"
        href: index.qmd
        
      - section: "Concepts"
        contents:
          - href: concepts/intervals.qmd
            text: "Confidence & Prediction Intervals"
          - href: concepts/distance_and_similarity.qmd
            text: "Distance and Similarity"
          - href: concepts/metrics.qmd
            text: "Model Metrics"
          - href: concepts/regularization.qmd
            text: "Regularization"

      - section: "Workflows"
        contents:
          - href: workflows/index.qmd
            text: "Workflows Index"
          - href: workflows/ds_workflow.qmd
            text: Data Science Project
          - href: workflows/classification_tabular.ipynb
            text: Classification
          - href: workflows/clustering_mixed_types.ipynb
            text: Clustering (Mixed Data)
          - href: workflows/forecasting_multi_univariate.ipynb
            text: Forecasting with ML
          - href: workflows/regression_tabular.ipynb
            text: Regression

      - text: "Common DS Problems"
        href: common_problems.qmd

      - text: "Glossary"
        href: glossary.qmd

      - text: "References"
        href: references.qmd
  navbar:
    tools:
      - icon: github
        menu:
          - text: GitHub Repository
            href:  https://github.com/dbolotov/ds-quickref


language: 
  search-text-placeholder: Search

format:
  html:
    link-external-newwindow: true
    theme:
      - materia
      - brand
      - styles.scss
    toc: true
    font:
      sans: "Segoe UI"
    fontsize: 1rem
    line-height: 1.6
    grid:
      sidebar-width: 400px
      body-width: 800px
      margin-width: 300px
      gutter-width: 2rem
    smooth-scroll: true
    # code-fold: true
    code-summary: "Show code"
    code-line-numbers: true

execute:
  enabled: true
  echo: true

