project:
  type: book

book:
  title: "DS QuickRef"
  subtitle: "A practical reference for machine learning, data science, and modeling workflows"
  author: "Dmitriy Bolotov"
  chapters:
    - index.qmd
    - part: "Workflows"
      chapters:
        - workflows/index.qmd
        - workflows/supervised_learning.ipynb
    - common_issues.qmd

    - glossary.qmd
    - references.qmd

format:
  html:
    theme:
      - flatly
      - brand
    toc: true
    css: styles.css

execute:
  enabled: true
