# **Data Science Quick Ref** {.unnumbered}

## About

This site is a concise, opinionated reference for practical data science and machine learning. It's built for students and professionals looking for summaries of key ideas, workflows, and tools.

All code examples are in Python, using libraries like `pandas`, `matplotlib`, `scikit-learn`, and `darts`. They are written to be easy to copy and adapt.

This is a work in progress, made by a data scientist who got tired of looking this stuff up frequently :)

## Usage
- Use the left sidebar to browse topics  
- Use the search bar to find specific terms or methods
- The **Concepts** section discusses topics around model building and evaluation, and contains links to resources as well as python code 
- The **Workflows** section contains a variety of starter templates for data science tasks, to be used for structuring a data analysis or model building project


## Author
Dmitriy Bolotov | <a href="https://dbolotov.github.io/" target="_blank">dbolotov.github.io</a>