# References {.unnumbered}

## Online Books & Educational Tools

::: {.small-table}

| Category          | Resource | Description |
|------------------|----------|-------------|
| Modeling | [An Introduction to Statistical Learning](https://www.statlearning.com/) | Statistical and machine learning approaches to learning from data. Includes companion website for [Python](https://islp.readthedocs.io/en/main/index.html) examples. |
| Explainability | [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/) | A practical overview of techniques for making ML models more transparent, including SHAP. |
| Visualization | [UW Interactive Data Lab Curriculum](https://idl.uw.edu/visualization-curriculum/intro.html) | Book on statistical visualization using Vega-Lite and Altair. |
| Visualization | [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) | Principles and examples of clear, effective visual communication. |
| Time Series | Forecasting: Principles and Practice: [R](https://otexts.com/fpp3/), [Python](https://otexts.com/fpppy/) | Comprehensive introduction to forecasting methods. Includes like exponential smoothing and ARIMA. Versions for R and Python available. |
| Data Imputation | [Flexible Imputation of Missing Data](https://stefvanbuuren.name/fimd/) | Methods to handle missing data, with emphasis on multiple imputation. |
| Fraud Detection | [Fraud Detection Handbook](https://fraud-detection-handbook.github.io/fraud-detection-handbook/Foreword.html) | Applied techniques for detecting fraud in highly imbalanced datasets. Includes instructions on using a fraud data simulator. |
| Statistics & Probability | [OpenIntro Statistics](https://www.openintro.org/book/os/) | Introduction to statistics and probability. Also includes links to YouTube videos explaining the concepts. |
| Statistics & Probability | [SeeingTheory](https://seeing-theory.brown.edu/) | Visual introduction to statistics and probability. |

:::

## Tools
- [SDV](https://github.com/sdv-dev/SDV) - Python library for creating tabular synthetic data.
- [permetrics](https://permetrics.readthedocs.io/en/latest/index.html#) - Python library for performance metrics of machine learning models. Documentation site includes quick explanations of each metric.

## Resources used to make this guide

- [Quarto](https://quarto.org/): Extensive publishing system. Supports jupyter notebooks and markdown.
- [bootswatch](https://bootswatch.com/): Collection of free themes for Bootstrap-based sites.


